version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskManagementSystem
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - backend

  webapi:
    image: webapi
    container_name: api 
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/taskManagementSystem
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - backend

networks:
  backend:
    name: backend-network
